---

- name: Percona Cluster
  hosts: db
  remote_user: ansible
  become: yes
  roles:
    - percona cluster

- name: Cai dat basic va LAMP
  hosts: all
  remote_user: ansible
  become: yes
  roles:
    - basic
    - LEMP
