---

#- name: cai WP
#  hosts: db
#  remote_user: ansible
#  become: yes
#  roles:
#    - wordpress

#- name: test ip lb
#  hosts: lb
#  remote_user: ansible
#  become: yes
#  roles:
#     - load_balancer

#- name: test KA
#  hosts: lb
#  remote_user: ansible
#  become: yes
#  roles:
#    - keepalived

- name: test HA
  hosts: lb
  remote_user: ansible
  become: yes
  roles:
    - load_balancer

