---
# tasks file for sync_db


- name: Lay master file va pos mysql cua server 1
  mysql_replication:
          login_host: "{{ database1['ip'] }}"
          login_user: "{{database1['replica']['username'] }}"
          login_password: "{{ database1['replica']['password'] }}"
          mode: getmaster
  register: mysql_repl_j1

- name: Change master host
  mysql_replication:
          master_host: "{{ database1['ip'] }}"
          # master_port: "{{mysql_repl_j1.Port}}"
          master_user: "{{database1['replica']['username']}}"
          master_password: "{{database1['replica']['password']}}"
          master_log_file: "{{mysql_repl_j1.File}}"
          master_log_pos: "{{mysql_repl_j1.Position}}"
          mode: changemaster
  notify:
          - restart mysql service

