---
# defaults file for keepalived

virtual_ipaddress: 103.109.43.43
master_interface: eth0 #interface card WAN
slave_interface: eth1

# Lay IP cua eth1 cua loadbalancer 
loadbalancer1_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + loadbalancer1_bind_interface]['ipv4']['address'] }}"
loadbalancer1_bind_interface: "eth1"
# Lay IP cua eth0 cua loadbalancer 
loadbalancer_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + loadbalancer_bind_interface]['ipv4']['address'] }}"
loadbalancer_bind_interface: "eth0"
#IP LAN loadbalancer 1
loadbalancer_ip1: "{{ hostvars[groups['lb'][0]]['ansible_' + loadbalancer1_bind_interface]['ipv4']['address'] }}"
#IP Lan loadbalancer 2
loadbalancer_ip2: "{{ hostvars[groups['lb'][1]]['ansible_' + loadbalancer_bind_interface]['ipv4']['address'] }}"
