---
 - name: them nginx repository
     apt_repository: repo='deb http://nginx.org/packages/ubuntu/ lucid nginx'

 - name: install nginx web server 
    apt:
      name: nginx
      state: latest
      force: yes

