---
# defaults file for load_balancer
load_balancer:
 config:
  maxconn: 812
  balance: roundrobin
  option: fowardfor

web:
 config:
  name_1: dangth-3
  name_2: dangth-4
  ip_1: 10.20.1.53
  ip_2: 10.20.1.61
