---
# defaults file for load_balancer
load_balancer:
 config:
  maxconn: 812
  balance: roundrobin
  option: httpclose

web:
 config:
  name_1: dangth-3
  name_2: dangth-4
  name_3: dangth-5
  ip_1: 10.20.1.53
  ip_2: 10.20.1.61
  ip_3: 10.20.1.29

stat_username: admin
stat_password: admin

# Lay IP cua eth1 cua loadbalancer 
loadbalancer1_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + loadbalancer1_bind_interface]['ipv4']['address'] }}"
loadbalancer1_bind_interface: "eth1"
# Lay IP cua eth0 cua loadbalancer 
loadbalancer_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + loadbalancer_bind_interface]['ipv4']['address'] }}"
loadbalancer_bind_interface: "eth0"
#IP LAN loadbalancer 1
loadbalancer_ip1: "{{ hostvars[groups['lb'][0]]['ansible_' + loadbalancer1_bind_interface]['ipv4']['address'] }}"
#IP Lan loadbalancer 2
loadbalancer_ip2: "{{ hostvars[groups['lb'][1]]['ansible_' + loadbalancer_bind_interface]['ipv4']['address'] }}"

