---
# tasks file for sync_db




- name: Lay master file va pos mysql cua server 2
  mysql_replication:
          login_host: "{{ database2['ip'] }}"
          login_user: "{{database2['replica']['username'] }}"
          login_password: "{{ database2['replica']['password'] }}"
          mode: getmaster
  register: mysql_repl_j2

- name: Change master host
  mysql_replication:
          master_host: "{{ database2['ip'] }}"
          # master_port: "{{mysql_repl_j2.Port}}"
          master_user: "{{database2['replica']['username']}}"
          master_password: "{{database2['replica']['password']}}"
          master_log_file: "{{mysql_repl_j2.File}}"
          master_log_pos: "{{mysql_repl_j2.Position}}"
          mode: changemaster
  notify:
          - restart mysql service

