---
# tasks file for load_balancer


- name: Cai dat Haproxy
  apt:
          name: haproxy
          state: present

- name: Enable Haproxy
  copy:
          src: haproxy
          dest: /etc/default/haproxy

- name: Config Haproxy
  template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg




