---
# filename: roles/mysql/tasks/install_Debian.yml
- name: Cai dat mysql server
  apt:
   name: "{{ mysql['pkg'][server] }}"
   update_cache: yes
- name: Cat dat mysql client
  apt:
    name: "{{ mysql['pkg']['server']}}"
    update_cache: yes
- name: Cai dat mysql python
  apt:
    name: "{{mysql['pkg']['python']}}"
